config-version: 1

EnvironmentalDamageList:
  - CONTACT
  - CRAMMING
  - DROWNING
  - DRYOUT
  - FALL
  - FALLING_BLOCK
  - FIRE
  - HOT_FLOOR
  - LIGHTNING
  - STARVATION
  - SUFFOCATION

Difficulty:
  easy:
    DamageTakenMultiplier: 0.75
    AttackDamageMultiplier: 1.25
    ExpMultiplier: 0.75
  normal:
    DamageTakenMultiplier: 1
    AttackDamageMultiplier: 1
    ExpMultiplier: 1
  hard:
    DamageTakenMultiplier: 1.25
    AttackDamageMultiplier: 0.75
    ExpMultiplier: 1.25
  custom_1:
    ExpMultiplier: 2
    EnvironmentMultiplier: 1.0
